#+TITLE: Styrmans dotfiles

* Table of Contents :toc:
- [[#what-are-dotfiles][What Are Dotfiles?]]
- [[#requirements][Requirements]]
- [[#install][Install]]
- [[#license][License]]

* What Are Dotfiles?
Dotfiles are the customization files that are used to personalize your Linux or other Unix-based system.  You can tell that a file is a dotfile because the name of the file will begin with a period--a dot!  The period at the beginning of a filename or directory name indicates that it is a hidden file or directory.  This repository contains my personal dotfiles.  They are stored here for convenience so that I may quickly access them on new machines or new installs.  Also, others may find some of my configurations helpful in customizing their own dotfiles.

* Requirements
You nead the folowing installed on your system.
- git
- stow


* Install

I use Gnu-stow to manage my dotfiles.

Clone my dotfiles to your system.
#+BEGIN_SRC bash
git clone https://github.com/styrman-g/dotfiles.git

# cd into my dotfiles
cd dotfiles

# Then use gnu stow to add the program you want to .config
# Example:
stow qtile

#+end_src


* License
The files and scripts in this repository are licensed under the MIT License, which is a very permissive license allowing you to use, modify, copy, distribute, sell, give away, etc. the software. In other words, do what you want with it. The only requirement with the MIT License is that the license and copyright notice must be provided with the software.
